### ISSUE TITLE
Upload through plugin manager does not work

### ISSUE THREAD

**Issue by DanielRuf** [mnaczenski/MNAddDSVGO#1]
``` 
Error
No Plugin found in archive.
```

**Comment by DanielRuf** [comment]
Ah it is because the directory inside of the zip file is wrong, it should be without the version part.

PS: It is DSGVO, not DSVGO
> Die Datenschutz-Grundverordnung (DSGVO)

**Comment by mnaczenski** [comment]
You can upload the file from the releases-tab of github.
Otherwhise you need to fullfill the shopware specific folder-name structure.

**Comment by DanielRuf** [comment]
> Ah it is because the directory inside of the zip file is wrong, it should be without the version part.

It was from the releases tab (as far as I remember). Also the zip includes `.git` and is not a "normal" release but just the source dir with the same content (the complete repo) ;-)

**Comment by DanielRuf** [comment]
```
zip-test wget https://github.com/mnaczenski/MNAddDSVGO/releases/download/1.3.1/MNAddDSVGO.zip
--2019-01-09 08:45:34--  https://github.com/mnaczenski/MNAddDSVGO/releases/download/1.3.1/MNAddDSVGO.zip
...
Saving to: ‘MNAddDSVGO.zip’

MNAddDSVGO.zip                                            100%[=====================================================================================================================================>]  38.09K   111KB/s    in 0.3s    

2019-01-09 08:45:36 (111 KB/s) - ‘MNAddDSVGO.zip’ saved [39003/39003]


➜  zip-test unzip MNAddDSVGO.zip 
Archive:  MNAddDSVGO.zip
   creating: MNAddDSVGO/
   creating: MNAddDSVGO/.git/
```

**Comment by DanielRuf** [comment]
But as it was just an example plugin, I guess I do not need it anymore and I can ignore these small issues.

Thanks for taking the time to give feedback.
