### ISSUE TITLE
Is this plugin still needed?

### ISSUE THREAD

**Issue by DanielRuf** [mnaczenski/MNAddDSVGO#2]
I see that the plugin adds several blocks for different templates but aren't these already available?

Because https://docs.shopware.com/de/shopware-5-de/einstellungen/datenschutz seems to provide these (in the core).

The readme of this plugin is not very understandable (it adds the tutorials to the theme?).

Is this now covered by the core and the docs or do we still need this plugin?

**Comment by mnaczenski** [comment]
This was an example for customers on how to implement these tutorials.
The plugin is only needed in old installations (prior 5.4.4), there might be better solutions in the store too.

**Comment by DanielRuf** [comment]
Ah ok, thanks for the clarification.
